### ISSUE TITLE
[FEAT] Cloud Run 환경 구성

### ISSUE THREAD

**Issue by TEDD325** [MLOps-CoinAssistant/MLOps-project#13]
## Background
 - Cloud Run 환경 구성을 위한 작업

## Todo
 - [x] GCP-IAM 작업 후, json 형식의 Key 받기
 - [ ] GCP-Artifact Store 생성하기
   - [ ] Dockerfile 작성
   - [ ] entrypoint.sh 작성
