### ISSUE TITLE
[FEAT] openAI API 파이프라인 작성

### ISSUE THREAD

**Issue by TEDD325** [MLOps-CoinAssistant/MLOps-project#18]
## Background
 - openAI API를 이용하여 뉴스 기사와 모델의 결과를 feeding하기 위한 파이프라인 작성

## Todo
 - [ ] openai 라이브러리 설치(requirements.txt)
 - [ ] openAI API 파이프라인 작성
 - [ ] openAI API의 결과를 데이터베이스에 적재
 - [ ] 배포 서버에 배포
