### ISSUE TITLE
[FEAT] 모델 학습 전처리를 위한 데이터 EDA

### ISSUE THREAD

**Issue by p65454** [MLOps-CoinAssistant/MLOps-project#25]
## Background
 - 업비트에서 가져온 1년치 데이터를 db로부터 호출해서 모델 학습을 위한 EDA
## Todo
 - [x] 데이터 갯수 확인
 - [x] 결측치 확인
 - [x] 중복 확인
 - [x] 이상치 확인
 - [x] 데이터 분포도 등 필요한 부분 시각화를 통해 확인
 - [x] 각 분야에 대해 어떻게 전처리할지 결정
     
## See also
 - 참고할 링크
