### ISSUE TITLE
[FEAT] 의존성 관리를 위한 airflow operator 변경 작업

### ISSUE THREAD

**Issue by p65454** [MLOps-CoinAssistant/MLOps-project#35]
## Background
 - 기존의 pythonoperator 를 사용시 여러 태스크에서 발생할 수 있는 라이브러리 충돌이나 의존성 문제를 방지하고자합니다.
   dockeroperator로 변경시 각각이 독립된 환경에서 실행되므로 이 부분이 해결될 것으로 예상됩니다.
## Todo
 - [x] 각 task에 필요한 라이브러리, 시스템 패키지파일 확인 후 requirements.txt 와 같은 파일에 각각 넣기
 - [x] 각 task에 필요한 도커파일 생성
 - [x] compose.yaml 에 위의 내용 빌드 할 수 있도록 코드 수정
 - [x] coin_price_api_pipeline.py 에 dockeroperator 사용할 수 있도록 코드 수정
 - [ ] 컨테이너 재실행 해서 잘 되는지 확인
     
## See also
 - feat/airflow-dockeroperator 브랜치에서 작업
