### ISSUE TITLE
[FIX] Rename pipeline and Revise coin_price_api_call and Add email pipeline at price pipeline

### ISSUE THREAD

**Issue by TEDD325** [MLOps-CoinAssistant/MLOps-project#38]
## Todo
 - [ ] coin_price_api_call.py에서 다음의 수정 사항
    - [ ] 쓰이지 않는 메서드 제거
    - [ ] 전역으로 관리되고 있는 session을 with문으로 관리하도록 변경
    - [ ] logger를 모두 주석처리(성능 고려)
 - [x] coin_price_api_pipeline.py에서 다음의 수정 사항
    - [x] coin_price_pipeline으로 파일명 수정
    - [x] 이메일 기능 추가
