### ISSUE TITLE
[FEAT] 전처리 함수 수정 및 기능 추가

### ISSUE THREAD

**Issue by p65454** [MLOps-CoinAssistant/MLOps-project#52]
## Background
 - 누락된 데이터에 대한 보간법 적용 및 자잘한 로직 수정
## Todo
 - [x] raw_data 갯수 및 오류 테스트
 - [x] 선형보간법 적용해서 누락된 데이터 대체하기
 - [ ] 수정 후 여러 상황에 대한 테스트
     
## See also
 - branch : feat/preprocessed-fix
