### ISSUE TITLE
[FIX] start.sh 파일 수정

### ISSUE THREAD

**Issue by TEDD325** [MLOps-CoinAssistant/MLOps-project#56]
## Background
 - start.sh 파일로 FastAPI 백엔드 서비스를 시작한다. 이 서비스를 시작하기 위해서는 최상위 디렉토리 내의 fastapi 폴더 내로 들어가서 실행해야 하는데 생각보다 번거롭다.
 -  또한, FastAPI를 실행시키기 위해 매번 conda activate해야하는 것도 번거롭다.
  
## Todo
 - [ ] start.sh의 위치를 디렉토리 최상단(FastAPI subproject의 바깥)으로 이동
 - [ ] start.sh의 파일 이름을 직관적으로 변경: backend-start.sh
 - [ ] FastAPI 외부로 옮겨진 start.sh로 FastAPI 백엔드 서비스를 실행시킬 수 있도록 하기 위해 shell 스크립트 수정
