### ISSUE TITLE
[FEAT] Pre-trained model을 MLFlow 아티팩트로 등록 후 추론 테스트

### ISSUE THREAD

**Issue by TEDD325** [MLOps-CoinAssistant/MLOps-project#69]
## Background
 - 유저 질문이 유의미한 질문인지 검사하기 위한 pre-trained 모델을 선정하고
 - 해당 모델을 MLflow를 통해 조회 및 추론 가능하도록 아티팩트로 등록하기 위함

## Todo
 - [x] HuggingFace API를 이용하여 pre-trained 모델 다운로드
 - [x] 모델을 올리기 위하여, GCS 세팅 및 Compute Engine 설정 변경
 - [x] 모델을 MLflow에 Artifact로 등록
 - [ ] FastAPI 엔드포인트로 추론 정의: MLflow를 통해 모델 호출 테스트
