### ISSUE TITLE
[FEAT] 예측모델 성능 향상을 위한 Feature engineering 

### ISSUE THREAD

**Issue by p65454** [MLOps-CoinAssistant/MLOps-project#70]
## Background
 - 성능향상을 위해 여러가지 피쳐를 추가해본다 (이동평균, rsi, 반감기 등)
## Todo
 - [x] 이동평균, RSI, MACD 등 기존 피쳐로 계산해서 만들 수 있는 피쳐들 만드는 코드 작성
 - [x] 에러 및 성능 테스트
 - [x] 반감기정보를 받아올 수 있는 무료API 요청 코드 작성
 - [x] 에러 및 성능 테스트
     
## See also
 - 참고할 링크
