### ISSUE TITLE
[FEAT] redis 캐시서버 및 에러핸들러 구현

### ISSUE THREAD

**Issue by p65454** [MLOps-CoinAssistant/MLOps-project#73]
## Background
 - 캐싱을 위한 redis 및 에러핸들링을 위한 클래스 정의 후 필요에 따라 적용
 
## Todo
 - [x] redis 서버 구현
 - [x] redis cache 적용
 - [x] 에러 클래스 만든 후 적용
 
## See also
 - 참고할 링크
