### ISSUE TITLE
[FEAT] 파이프라인 분리

### ISSUE THREAD

**Issue by p65454** [MLOps-CoinAssistant/MLOps-project#88]
## Background
 - 자원 소모 및 효율을 위해 데이터, 학습, 트리거 를 위한 각각의 dag파일을 만들어서 파이프라인을 분리해야한다.
## Todo
 - [x] 데이터 파이프라인 분리
 - [x] 모델학습 파이프라인 분리
 - [x] 모니터링 & 트리거 파이프라인 분리
 - [x] 테스트
     
## See also
 - 참고할 링크
